import { useEffect, useMemo, useState } from 'react';
import { useCircuitStore } from '../stores/circuit.js';
import { useSimulationStore } from '../stores/simulation.js';
import type { CircuitComponent } from '../core/model.js';

interface Size { w:number; h:number; }
const SIZES: Record<string,Size> = {
  ground:{w:46,h:42},'dc-source':{w:64,h:46},resistor:{w:72,h:34},led:{w:58,h:58},diode:{w:56,h:32},capacitor:{w:54,h:44},inductor:{w:68,h:34},potentiometer:{w:70,h:54},zener:{w:56,h:32},'bjt-npn':{w:58,h:58},'mosfet-n':{w:62,h:58},and:{w:82,h:52},not:{w:74,h:48},'arduino-uno':{w:190,h:112},'analog-sensor':{w:74,h:62},pushbutton:{w:60,h:60},'dc-motor':{w:70,h:60},servo:{w:82,h:70},'lcd-1602':{w:154,h:86},'i2c-temp':{w:78,h:58},'i2c-eeprom':{w:78,h:58},'spi-dac':{w:84,h:62},'spi-flash':{w:84,h:62},
};

const ROOT: React.CSSProperties={position:'absolute',inset:0,overflow:'hidden',pointerEvents:'none',zIndex:2};
const card=(selected:boolean):React.CSSProperties=>({position:'absolute',boxSizing:'border-box',border:selected?'2px solid #f78166':'1px solid rgba(12,18,24,.75)',boxShadow:selected?'0 0 0 2px rgba(247,129,102,.16),0 8px 18px rgba(0,0,0,.35)':'0 6px 14px rgba(0,0,0,.3)',transformStyle:'preserve-3d'});
const label=(text:string,scale:number)=><div style={{position:'absolute',left:0,right:0,bottom:-15*scale,textAlign:'center',color:'#d6dee6',fontFamily:'monospace',fontSize:Math.max(7,9*scale),whiteSpace:'nowrap'}}>{text}</div>;

function Generic({comp,selected}:{comp:CircuitComponent;selected:boolean}){
  const s=SIZES[comp.type]??{w:64,h:44};
  const palette:Record<string,[string,string]>={
    ground:['#4e5962','#1d242a'],'dc-source':['#c9ced4','#68727b'],capacitor:['#a9b2bb','#5e6973'],inductor:['#b36a34','#4d2c16'],potentiometer:['#33414c','#121820'],diode:['#26313a','#141b21'],zener:['#202a33','#0d141a'],'bjt-npn':['#2d3238','#0e1418'],'mosfet-n':['#252c33','#0c1116'],and:['#20262d','#0b0f13'],not:['#20262d','#0b0f13'],'analog-sensor':['#4d8bc0','#19344f'],pushbutton:['#d6d9dd','#6b737b'],'i2c-temp':['#202a31','#0c1217'],'i2c-eeprom':['#202a31','#0c1217'],'spi-dac':['#2d5f82','#122638'],'spi-flash':['#252f39','#0d141b']};
  const [a,b]=palette[comp.type]??['#343b43','#171c22'];
  const state=comp.type==='pushbutton'?(Boolean(comp.params.pressed)?'PRESSED':'RELEASED'):comp.type.toUpperCase();
  return <div style={{...card(selected),width:s.w,height:s.h,borderRadius:7,background:`linear-gradient(145deg,${a},${b})`,display:'grid',placeItems:'center'}}><div style={{width:s.w*.62,height:s.h*.42,borderRadius:5,background:'rgba(255,255,255,.07)',border:'1px solid rgba(255,255,255,.12)',display:'grid',placeItems:'center',color:'#e6edf3',fontWeight:800,fontSize:10}}>{state}</div>{label(comp.type,1)}</div>;
}

function Led({brightness,selected}:{brightness:number;selected:boolean}){const on=brightness>.03;return <div style={{...card(selected),width:58,height:58,borderRadius:'50%',background:'transparent',boxShadow:on?'0 0 24px rgba(255,40,40,.78),0 0 55px rgba(255,30,30,.38)':card(selected).boxShadow}}><div style={{position:'absolute',left:11,top:7,width:36,height:40,borderRadius:'50% 50% 46% 46%',background:on?'radial-gradient(circle at 35% 28%,#fff6f6 0%,#ff8f8f 14%,#ff2d2d 48%,#9a1010 100%)':'radial-gradient(circle at 35% 28%,#f7d8d8 0%,#d66666 20%,#7d1a1a 70%,#461010 100%)',border:'1px solid rgba(70,10,10,.8)'}}/><div style={{position:'absolute',left:25,top:45,width:2,height:12,background:'#c4ccd2'}}/><div style={{position:'absolute',left:15,top:47,width:2,height:9,background:'#c4ccd2'}}/>{on&&<span style={{position:'absolute',inset:0,display:'grid',placeItems:'center',color:'#fff',fontSize:9,fontWeight:800,textShadow:'0 1px 2px #600'}}>ON</span>}{label('LED',1)}</div>}
function Resistor({value,selected}:{value:number;selected:boolean}){return <div style={{...card(selected),width:72,height:34,borderRadius:8,background:'linear-gradient(180deg,#f5e5bf,#b69262)'}}><div style={{position:'absolute',left:-12,top:15,width:16,height:2,background:'#b9c4cd'}}/><div style={{position:'absolute',right:-12,top:15,width:16,height:2,background:'#b9c4cd'}}/>{[.27,.44,.61,.78].map((x,i)=><div key={i} style={{position:'absolute',left:72*x-2,top:0,width:4,height:34,background:['#7e3d16','#171717','#7e3d16','#d6be78'][i]}}/>)}{label(`${value}Ω`,1)}</div>}
function Arduino({selected,on}:{selected:boolean;on:boolean}){return <div style={{...card(selected),width:190,height:112,borderRadius:8,background:'linear-gradient(145deg,#49a967,#197040 48%,#0f4c2b)',overflow:'visible'}}><div style={{position:'absolute',left:-12,top:18,width:24,height:22,borderRadius:3,background:'linear-gradient(#c6ccd1,#6d767e)'}}/><div style={{position:'absolute',left:22,top:26,width:58,height:38,borderRadius:4,background:'#12181d'}}/><div style={{position:'absolute',left:86,top:34,fontSize:11,fontWeight:800,color:'#10261a'}}>ARDUINO UNO</div><div style={{position:'absolute',left:88,top:52,fontSize:8,color:'#b8ddc4'}}>ATmega328P</div><div style={{position:'absolute',right:16,top:18,width:6,height:6,borderRadius:'50%',background:on?'#ff4a4a':'#412b2b',boxShadow:on?'0 0 10px #ff3434':'none'}}/>{Array.from({length:10},(_,i)=><div key={i} style={{position:'absolute',left:24+i*16,top:-9,width:6,height:12,background:'linear-gradient(90deg,#d8dce0,#7f878e)',borderRadius:2}}/>)}>{label('Arduino Uno',1)}</div>}
function LCD({text,contrast,selected}:{text:string;contrast:number;selected:boolean}){const row1=text.slice(0,16).padEnd(16,' '),row2=text.slice(16,32).padEnd(16,' ');return <div style={{...card(selected),width:154,height:86,borderRadius:8,background:'linear-gradient(180deg,#d9dde2,#8d97a1)',padding:10}}><div style={{position:'absolute',left:10,top:10,right:10,height:44,borderRadius:3,background:`linear-gradient(180deg,rgba(115,228,124,${.45+.35*contrast}),rgba(27,76,37,.95))`,boxShadow:`inset 0 0 8px rgba(0,0,0,.55),0 0 8px rgba(75,255,110,${.12+.2*contrast})`}}><div style={{fontFamily:'monospace',fontSize:10,lineHeight:'16px',color:'#8cff9d',textShadow:'0 0 5px rgba(130,255,150,.65)',padding:'4px 6px',whiteSpace:'pre'}}>{row1}<br/>{row2}</div></div>{Array.from({length:4},(_,i)=><div key={i} style={{position:'absolute',left:15+i*16,bottom:-10,width:5,height:12,background:'#ca943c'}}/>)}{label('16×2 LCD',1)}</div>}
function Motor({speed,selected}:{speed:number;selected:boolean}){const [angle,setAngle]=useState(0);useEffect(()=>{let raf=0;const tick=()=>{setAngle(a=>a+0.08*(1+speed/10));raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[speed]);return <div style={{...card(selected),width:70,height:60,borderRadius:8,background:'linear-gradient(180deg,#c9ced4,#747c85)',display:'grid',placeItems:'center'}}><div style={{width:34,height:34,borderRadius:'50%',background:'#8b949e',border:'2px solid #4c535a',position:'relative'}}><div style={{position:'absolute',left:'50%',top:'50%',width:28,height:4,background:'#30373d',transformOrigin:'center',transform:`translate(-50%,-50%) rotate(${angle}rad)`}}/></div>{label(`${Math.round(speed)}%`,1)}</div>}
function Servo({angle,selected}:{angle:number;selected:boolean}){const a=(-90+Math.max(0,Math.min(180,angle)))*Math.PI/180;return <div style={{...card(selected),width:82,height:70,borderRadius:7,background:'linear-gradient(180deg,#343b43,#1e252c)',display:'grid',placeItems:'center'}}><div style={{width:32,height:32,borderRadius:'50%',background:'#707981',border:'1px solid #aab2ba',position:'relative'}}><div style={{position:'absolute',left:'50%',top:'50%',width:25,height:5,background:'#e1e6eb',borderRadius:3,transformOrigin:'left center',transform:`translateY(-50%) rotate(${a}rad)`}}/></div>{Array.from({length:3},(_,i)=><div key={i} style={{position:'absolute',left:12+i*12,bottom:-7,width:7,height:9,background:['#e6e6e6','#cd9b3b','#d75252'][i],borderRadius:2}}/>)}{label('Servo',1)}</div>}

export function PhysicalComponentsOverlay(){
  const components=useCircuitStore(s=>s.components); const selection=useCircuitStore(s=>s.selection); const viewport=useCircuitStore(s=>s.viewport); const dcResult=useSimulationStore(s=>s.dcResult); const arduinoResult=useSimulationStore(s=>s.arduinoResult);
  const physical=useMemo(()=>[...components.values()],[components]);
  const pulse=arduinoResult?.state.transitions ?? [];
  const d13On=Boolean(arduinoResult?.state.digital[13]) || (pulse.length>0 && pulse[pulse.length-1].pin===13 && pulse[pulse.length-1].value===1);
  return <div style={ROOT} aria-hidden="true"><div style={{position:'absolute',inset:0,transformOrigin:'0 0',transform:`translate(${-viewport.x*viewport.zoom}px,${-viewport.y*viewport.zoom}px) scale(${viewport.zoom})`,pointerEvents:'none'}}>{physical.map(comp=>{
    const s=physicalSize(comp); const selected=selection.componentIds.has(comp.id); const base:React.CSSProperties={...card(selected),left:comp.position.x,top:comp.position.y,width:s.w,height:s.h,transform:`translate(-50%,-50%) rotate(${comp.rotation||0}deg)`,transformOrigin:'center',pointerEvents:'none'};
    if(comp.type==='led'){const dev=(dcResult?.devBranches as any[]|undefined)?.find(v=>v.compId===comp.id);const current=typeof dev?.current==='number'?Math.abs(dev.current):0;return <div key={comp.id} style={base}><Led brightness={Math.max(current/0.02,d13On?1:0)} selected={false}/></div>}
    if(comp.type==='resistor')return <div key={comp.id} style={base}><Resistor value={Number(comp.params.resistance??220)} selected={false}/></div>;
    if(comp.type==='arduino-uno')return <div key={comp.id} style={base}><Arduino selected={false} on={d13On}/></div>;
    if(comp.type==='lcd-1602')return <div key={comp.id} style={base}><LCD text={arduinoResult?.state.lcd.text||String(comp.params.text??'')} contrast={Number(comp.params.contrast??.5)} selected={false}/></div>;
    if(comp.type==='dc-motor')return <div key={comp.id} style={base}><Motor speed={Number(comp.params.speed??0)} selected={false}/></div>;
    if(comp.type==='servo')return <div key={comp.id} style={base}><Servo angle={Number(comp.params.angle??90)} selected={false}/></div>;
    return <div key={comp.id} style={base}><Generic comp={comp} selected={false}/></div>;
  })}</div></div>;
}
